global:
  scrape_interval: 5s # 5초마다 데이터 수집

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker-containers'
    static_configs:
      # cAdvisor 컨테이너의 포트(8080)를 바라봄
      - targets: ['cadvisor:8080']